// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(1,
      "name", v_str("BluefinDecryptx")),
    "feature", cmap(1,
      "test", cmap(1,
        "options", cmap(1,
          "active", v_bool(false)))),
    "options", cmap(4,
      "base", v_str("https://secure-prod.decryptx.com/api"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(3,
        "decrypt", v_map(),
        "decrypt_ext", v_map(),
        "validation", v_map()),
      "auth", cmap(1,
        "prefix", v_str(""))),
    "entity", cmap(3,
      "decrypt", cmap(4,
        "fields", clist(17,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("code"),
            "req", v_bool(false),
            "type", v_str("`$INTEGER`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("decrypted"),
            "req", v_bool(false),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("decryption_parameter"),
            "req", v_bool(true),
            "type", v_str("`$OBJECT`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("encrypted"),
            "req", v_bool(true),
            "type", v_str("`$ARRAY`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("failed"),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("firmware"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("has_cc_data"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(7)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("message"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("message_id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(10)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(11)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner_key"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(12)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("reference"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(13)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("serial"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(14)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("success"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(15)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("value"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(16))),
        "name", v_str("decrypt"),
        "op", cmap(2,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("POST"),
                "orig", v_str("/decrypt"),
                "parts", clist(1,
                  v_str("decrypt")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create")),
          "list", cmap(4,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", cmap(1,
                  "query", clist(7,
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("client_id"),
                      "orig", v_str("client_id"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_str("param 1"),
                      "kind", v_str("query"),
                      "name", v_str("encrypted_name"),
                      "orig", v_str("encrypted_name"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(7,
                      "active", v_bool(true),
                      "example", v_str("nlj/tULUuiMlM3io0JZ+9jFBTKH7KCPwVg7PFjvWUMzMa7XE/QbegA=="),
                      "kind", v_str("query"),
                      "name", v_str("encrypted_value"),
                      "orig", v_str("encrypted_value"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner_id"),
                      "orig", v_str("partner_id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("partner_key"),
                      "orig", v_str("partner_key"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("reference"),
                      "orig", v_str("reference"),
                      "reqd", v_bool(false),
                      "type", v_str("`$STRING`")),
                    cmap(6,
                      "active", v_bool(true),
                      "kind", v_str("query"),
                      "name", v_str("serial"),
                      "orig", v_str("serial"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "method", v_str("GET"),
                "orig", v_str("/healthcheck"),
                "parts", clist(1,
                  v_str("healthcheck")),
                "select", cmap(1,
                  "exist", clist(7,
                    v_str("client_id"),
                    v_str("encrypted_name"),
                    v_str("encrypted_value"),
                    v_str("partner_id"),
                    v_str("partner_key"),
                    v_str("reference"),
                    v_str("serial"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("list"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "decrypt_ext", cmap(4,
        "fields", clist(11,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("completed"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("decrypted"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$NUMBER`"))),
            "req", v_bool(false),
            "type", v_str("`$NUMBER`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("encrypted"),
            "req", v_bool(true),
            "type", v_str("`$NUMBER`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("ip"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("message_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner_id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner_key"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(7)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("reference"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$STRING`"))),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(8)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("serial"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(9)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("success"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(true),
                "type", v_str("`$BOOLEAN`"))),
            "req", v_bool(false),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(10))),
        "name", v_str("decrypt_ext"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("POST"),
                "orig", v_str("/decrypt-ext"),
                "parts", clist(1,
                  v_str("decrypt-ext")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "validation", cmap(4,
        "fields", clist(8,
          cmap(5,
            "active", v_bool(true),
            "name", v_str("client_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(0)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("firmware"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(1)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("message_id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(2)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner_id"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(3)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("partner_key"),
            "req", v_bool(false),
            "type", v_str("`$STRING`"),
            "index$", v_num(4)),
          cmap(6,
            "active", v_bool(true),
            "name", v_str("reference"),
            "op", cmap(1,
              "create", cmap(2,
                "req", v_bool(false),
                "type", v_str("`$STRING`"))),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(5)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("serial"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"),
            "index$", v_num(6)),
          cmap(5,
            "active", v_bool(true),
            "name", v_str("success"),
            "req", v_bool(true),
            "type", v_str("`$BOOLEAN`"),
            "index$", v_num(7))),
        "name", v_str("validation"),
        "op", cmap(1,
          "create", cmap(4,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("POST"),
                "orig", v_str("/device/validate"),
                "parts", clist(2,
                  v_str("device"),
                  v_str("validate")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(0)),
              cmap(8,
                "active", v_bool(true),
                "args", v_map(),
                "method", v_str("POST"),
                "orig", v_str("/partner/validate"),
                "parts", clist(2,
                  v_str("partner"),
                  v_str("validate")),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "index$", v_num(1))),
            "key$", v_str("create"))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

Feature* make_feature(const char* name) {
  if (strcmp(name, "audit") == 0) return feature_audit_new();
  if (strcmp(name, "cache") == 0) return feature_cache_new();
  if (strcmp(name, "clienttrack") == 0) return feature_clienttrack_new();
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "log") == 0) return feature_log_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "netsim") == 0) return feature_netsim_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "proxy") == 0) return feature_proxy_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "rbac") == 0) return feature_rbac_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "streaming") == 0) return feature_streaming_new();
  if (strcmp(name, "telemetry") == 0) return feature_telemetry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}
