package voxgig.bluefindecryptxsdk.core

import voxgig.bluefindecryptxsdk.utility.Json

/** Static SDK configuration and by-name feature construction. */
@Suppress("UNCHECKED_CAST")
object Config {

  fun makeConfig(): MutableMap<String, Any?> {
    return Json.parse(configJson()) as MutableMap<String, Any?>
  }

  fun makeFeature(name: String): Feature {
    return when (name) {
      "test" -> voxgig.bluefindecryptxsdk.feature.TestFeature()
      else -> voxgig.bluefindecryptxsdk.feature.BaseFeature()
    }
  }

  private fun configJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"BluefinDecryptx\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://secure-prod.decryptx.com/api\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"decrypt\": {},")
    b.append("   \"decrypt_ext\": {},")
    b.append("   \"validation\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"decrypt\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"client_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"code\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$INTEGER`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"decrypted\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"decryption_parameter\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$OBJECT`\",")
    b.append("     \"index\$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"encrypted\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$ARRAY`\",")
    b.append("     \"index\$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"failed\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$BOOLEAN`\",")
    b.append("     \"index\$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"firmware\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"has_cc_data\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$BOOLEAN`\",")
    b.append("     \"index\$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 8")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 9")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"name\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 10")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"partner_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 11")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"partner_key\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 12")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": false,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 13")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"serial\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 14")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"success\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$BOOLEAN`\",")
    b.append("     \"index\$\": 15")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"value\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 16")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"decrypt\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/decrypt\",")
    b.append("       \"parts\": [")
    b.append("        \"decrypt\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    },")
    b.append("    \"list\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"list\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"query\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"client_id\",")
    b.append("          \"orig\": \"client_id\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"example\": \"param 1\",")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"encrypted_name\",")
    b.append("          \"orig\": \"encrypted_name\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"example\": \"nlj/tULUuiMlM3io0JZ+9jFBTKH7KCPwVg7PFjvWUMzMa7XE/QbegA==\",")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"encrypted_value\",")
    b.append("          \"orig\": \"encrypted_value\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner_id\",")
    b.append("          \"orig\": \"partner_id\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"partner_key\",")
    b.append("          \"orig\": \"partner_key\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"reference\",")
    b.append("          \"orig\": \"reference\",")
    b.append("          \"reqd\": false,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         },")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"query\",")
    b.append("          \"name\": \"serial\",")
    b.append("          \"orig\": \"serial\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/healthcheck\",")
    b.append("       \"parts\": [")
    b.append("        \"healthcheck\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"client_id\",")
    b.append("         \"encrypted_name\",")
    b.append("         \"encrypted_value\",")
    b.append("         \"partner_id\",")
    b.append("         \"partner_key\",")
    b.append("         \"reference\",")
    b.append("         \"serial\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"list\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"decrypt_ext\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"client_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"completed\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"decrypted\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$NUMBER`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$NUMBER`\",")
    b.append("     \"index\$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"encrypted\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$NUMBER`\",")
    b.append("     \"index\$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"ip\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"partner_id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"partner_key\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 8")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"serial\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 9")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"success\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": true,")
    b.append("       \"type\": \"`\$BOOLEAN`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$BOOLEAN`\",")
    b.append("     \"index\$\": 10")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"decrypt_ext\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/decrypt-ext\",")
    b.append("       \"parts\": [")
    b.append("        \"decrypt-ext\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"validation\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"client_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"firmware\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"message_id\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"partner_id\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"partner_key\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"reference\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": false,")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"serial\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$STRING`\",")
    b.append("     \"index\$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"success\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`\$BOOLEAN`\",")
    b.append("     \"index\$\": 7")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"validation\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/device/validate\",")
    b.append("       \"parts\": [")
    b.append("        \"device\",")
    b.append("        \"validate\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/partner/validate\",")
    b.append("       \"parts\": [")
    b.append("        \"partner\",")
    b.append("        \"validate\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index\$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key\$\": \"create\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    return b.toString()
  }
}
