;; BluefinDecryptx SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.decrypt :as e-decrypt]
            [sdk.entity.decrypt_ext :as e-decrypt_ext]
            [sdk.entity.validation :as e-validation]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)

;; Decrypt accessor: (decrypt client data)
(defn decrypt [client data] (e-decrypt/make client data))

;; DecryptExt accessor: (decrypt_ext client data)
(defn decrypt_ext [client data] (e-decrypt_ext/make client data))

;; Validation accessor: (validation client data)
(defn validation [client data] (e-validation/make client data))
