;; BluefinDecryptx SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "decrypt" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "client_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "code"
            "req" false
            "type" "`$INTEGER`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "decrypted"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "decryption_parameter"
            "req" true
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "encrypted"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "failed"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "firmware"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "has_cc_data"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "message"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "message_id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "name"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "partner_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "partner_key"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "reference"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "serial"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "success"
            "req" true
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "value"
            "req" false
            "type" "`$STRING`"))
        "name" "decrypt"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/decrypt"
                "parts" (vs/jt
                  "decrypt")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "list" (vs/jm
            "input" "data"
            "key$" "list"
            "name" "list"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "query" (vs/jt
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "client_id"
                      "orig" "client_id"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "param 1"
                      "kind" "query"
                      "name" "encrypted_name"
                      "orig" "encrypted_name"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "example" "nlj/tULUuiMlM3io0JZ+9jFBTKH7KCPwVg7PFjvWUMzMa7XE/QbegA=="
                      "kind" "query"
                      "name" "encrypted_value"
                      "orig" "encrypted_value"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner_id"
                      "orig" "partner_id"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "partner_key"
                      "orig" "partner_key"
                      "reqd" true
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "reference"
                      "orig" "reference"
                      "reqd" false
                      "type" "`$STRING`")
                    (vs/jm
                      "active" true
                      "kind" "query"
                      "name" "serial"
                      "orig" "serial"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/healthcheck"
                "parts" (vs/jt
                  "healthcheck")
                "select" (vs/jm
                  "exist" (vs/jt
                    "client_id"
                    "encrypted_name"
                    "encrypted_value"
                    "partner_id"
                    "partner_key"
                    "reference"
                    "serial"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "decrypt_ext" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "client_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "completed"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "decrypted"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$NUMBER`"))
            "req" false
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "encrypted"
            "req" true
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "ip"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "message_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "partner_id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "partner_key"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "reference"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$STRING`"))
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "serial"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "success"
            "op" (vs/jm
              "create" (vs/jm
                "req" true
                "type" "`$BOOLEAN`"))
            "req" false
            "type" "`$BOOLEAN`"))
        "name" "decrypt_ext"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/decrypt-ext"
                "parts" (vs/jt
                  "decrypt-ext")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "validation" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "client_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "firmware"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "message_id"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "partner_id"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "partner_key"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "reference"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "serial"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "success"
            "req" true
            "type" "`$BOOLEAN`"))
        "name" "validation"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/device/validate"
                "parts" (vs/jt
                  "device"
                  "validate")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "POST"
                "orig" "/partner/validate"
                "parts" (vs/jt
                  "partner"
                  "validate")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "BluefinDecryptx")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "")
      "base" "https://secure-prod.decryptx.com/api"
      "entity" (vs/jm
        "decrypt" (vs/jm)
        "decrypt_ext" (vs/jm)
        "validation" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
